version: "3"
services:
  backend:
    image: node:17.1.0-alpine
    container_name: watermark_backend 
    working_dir: /usr/app
    entrypoint: /entrypoint.sh
    command: npm start
    volumes:
      - ./Backend:/usr/app
      - ./Backend/entrypoint.sh:/entrypoint.sh
    ports: 
      - '8088:8088' 
  
  frontend:
    image: node:17.1.0-alpine
    container_name: watermark_frontend
    user: $DOCKER_USER # mandatory for node_modules chown
    working_dir: /app
    entrypoint: /entrypoint.sh
    command: "npm run serve"
    volumes:
      - ./Frontend:/app
      - ./Frontend/entrypoint.sh:/entrypoint.sh
    ports:
      - '8080:8080'